### ISSUE TITLE
v0.33.1 breaks Remix applications using polyfills in NodeJs

### ISSUE THREAD

**Issue by MattyBalaam** [mswjs/interceptors#649]
After upgrading from msw v2.4.3 to  v2.4.4 our remix apps using MSW started failing with no data being returned from remix loaders. 

I then narrowed it down to a change in @mswjs/interceptors from v0.33.0 to v0.33.1

I am not sure exactly what the issue is, but after comparing the changes, I have been able to stop the regression by removing a call to `recordRawFetchHeaders`

<img width="531" alt="Screenshot 2024-10-01 at 14 16 41" src="https://github.com/user-attachments/assets/160feb3c-438b-49ff-8593-e820ff4ef3e1">

This was added here: https://github.com/mswjs/interceptors/commit/4660558f27e610063ff204ccf4a7595082040a0b#diff-58118abd89f14c6d555b9972de91edd6eeca4ccb3bd73ce0724bc9af9d595281

I have narrowed this down further to us using Remix’s `installGlobals` in our vite config - we can’t use the node build-in fetch in our case because we need to use the `host` header

**Comment by MattyBalaam** [comment]
I have attempted to replace using installGlobals by adding `undici` and directly importing their fetch implementation

Do you think the issue might be with them?

**Comment by MattyBalaam** [comment]
Some more digging, If I go into the remix code which enables specific polyfills they replace `global.Headers` in Node with this: https://github.com/remix-run/web-std-io/blob/main/packages/fetch/src/headers.js

**Comment by kettanaito** [comment]
Hi. Thanks for reporting this.
I believe this has been addressed. Could you please update to the latest version of the package and let me know?

**Comment by MattyBalaam** [comment]
It was actually the bump up to MSW v2.4.9 which showed the issue, but I narrowed down the issue to starting with v2.4.4

I just forced  `@mswjs/interceptors` to `0.36.0` (using msw  v2.4.9 ) with yarn resolutions but the issue persists.

**Comment by kettanaito** [comment]
Gotcha. Then it's a new issue. Could you please provide a reproduction repo for me to see it happening? You can fork our [Remix example](https://github.com/mswjs/examples/tree/main/examples/with-remix) and start from there. Feel free to update the MSW/Remix versions to suit your scenario. Would be happy to look into it then. Thanks.

**Comment by MattyBalaam** [comment]
I couldn’t get the remix example working in code sandbox at all (skill issue I’m sure) but I ended up pulling out bits of it into an install of the latest remix and have a reproduction: https://github.com/MattyBalaam/msw-remix-issue

What I have realised is that this is only an issue if I use `installGlobals();`in the `vite.config.ts` to polyfill the fetch implementation. In my case unfortunately I need to do this because the app accesses some APIs which specificially require a custom `HOST` header, and the native fetch does not allow this for security reasons.

What seems to happen is that in the polyfill version if I log out into the JS with `	{JSON.stringify(loaderData)}` the result is:

`"{\"serverSideData\":{\"firstName\":\"John\",\"lastName\":\"Maverick\"},\"test\":\"Hello\"}"`

But without the polyfill enabled it is:

`{"serverSideData":{"firstName":"John","lastName":"Maverick"},"test":"Hello"}`

**Comment by PilatP** [comment]
Testing remix app have an issue. The headers in the response are empty
```
Response {
  size: 0,
  [Symbol(Body internals)]: {
    body: null,
    type: null,
    size: 0,
    boundary: null,
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: undefined,
    status: 302,
    statusText: '',
    headers: {},
    counter: 0,
    highWaterMark: undefined
  }
}
```
Reverting to 
```
  "resolutions": {
    "@mswjs/interceptors": "0.33.0"
  }
```
helps with the headers
```
Response {
  size: 0,
  [Symbol(Body internals)]: {
    body: null,
    type: null,
    size: 0,
    boundary: null,
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: undefined,
    status: 302,
    statusText: '',
    headers: { location: 'weekly' },
    counter: 0,
    highWaterMark: undefined
  }
}
```
